### ISSUE TITLE
PowerSHELL's Permission Denied (Again)

### ISSUE THREAD

**Issue by JeanShuralyov** [hollowaykeanho/Upscaler#23]
# Description
```
Please provide a short description of what you have encountered below.
```
Apparently, somewhere along the road, the powerSHELL permission got removed from the `start.cmd` file. We have to restore it back.

# Expected Behavior
```
Please specify the expected behavior of your usage below.
```
`start.cmd` can run without permission denial. Reference: https://superuser.com/questions/106360/how-to-enable-execution-of-powershell-scripts

```
powershell.exe -noprofile -executionpolicy bypass -file .\script.ps1
```

# Current Behavior
```
Please specify the current behavior of software below.
```
Permission denied. Have to manually add that `-executionpolicy bypass` into `start.cmd`.

# Steps to Reproduce (COMPULSORY)
```
Please specify all the steps required to re-produce the problem.
```
1. Download `sources.zip` version `v0.6.0`.
2. Install FFMPEG and VC redistributable dependencies.
3. Run `tests\benchmark.cmd`.
4. Observe the error.

# Attachments
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
Issue confirmed: https://github.com/hollowaykeanho/Upscaler/commit/d64c62f5de7f5f55c87432de601d688f11d144fe#diff-8c766ef448b8c2cf31a240ec14ec7d65e15f7be65b5b9e4a65bb9285391502f4

The above commit accidentally removed bypass permission from the `start.cmd` .

**Comment by hollowaykeanho** [comment]
patch merged. Pending release.

**Comment by JeanShuralyov** [comment]
So fast.

**Comment by hollowaykeanho** [comment]
Resolved.
