### ISSUE TITLE
Windows Has VC C++ Dependency

### ISSUE THREAD

**Issue by JeanShuralyov** [hollowaykeanho/Upscaler#24]
# Description
```
Please provide a short description of what you have encountered below.
```
On a plain Windows startup, one has to install VC C++ dependency in order to use the Upscaler. This is not documented as no one experience this beforehand.

# Expected Behavior
```
Please specify the expected behavior of your usage below.
```
The VC C++ dependency is documented.

# Current Behavior
```
Please specify the current behavior of software below.
```
VC C++ dependency is not documented.

# Steps to Reproduce (COMPULSORY)
```
Please specify all the steps required to re-produce the problem.
```
1. Buy a new laptop.
2. Download the upscaler.
3. Run `tests/benchmark.cmd`. An error occured stating `MSVCP110D.dll ` or something from the package is missing.

# Attachments
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
Acknowledged. You know what to do.

**Comment by hollowaykeanho** [comment]
Patching received. Pending release.

**Comment by hollowaykeanho** [comment]
Released.
