### ISSUE TITLE
sorry for stupid question, how to run on linux

### ISSUE THREAD

**Issue by jaydenchan1027** [hollowaykeanho/Upscaler#62]
# Question
```
Please state your question in a brief and ended with question mark (?). You
may include sub-questions with "if cases" to communicate more effectively
instead of many 'ping-pong' passing.
```

# Background
```
Please provide a short description of what you are trying to ask.
```

# Current Research Artifacts (COMPULSORY)
```
Please list out all your research artifacts that you did (e.g. link, blog post,
documentations, and etc) for us to gauge your context and current efforts. We
may not reply and will close the ticket with perjuidice if this section remains
empty and unconvincing.
```

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
Hi there!

Depending on how to install (I recommend `git clone` the repo). Then run the `start.cmd` like a bash script. The file extension is mainly for operating on Windows (it's a polygot script).

`$ ./start.cmd --help` will provide some command helpers.

**Comment by hollowaykeanho** [comment]
Closing this ticket since there isn't any reply for 2 weeks - assuming answered. Should you need to clarify more, please open a new issue ticket.
