### ISSUE TITLE
Regarding the use of start.cmd

### ISSUE THREAD

**Issue by mflyskym1** [hollowaykeanho/Upscaler#88]
### Description

Hello, my friend

I encountered a problem while using Upscaler and sought help. I sent you an email but didn't see your reply! The specific issues are as follows:

I have downloaded the latest version of Upscaler 0.7 and also configured the environment variables for the OS system. I have installed the C++runtime library support and video processing plugins, but an error occurred when running start.cmd (as shown in the picture below). At the same time, I searched for the ini \ windows.ps1 file but couldn't find the problem. Please follow my path and optimize how to write the start.cmd and run.bat files.

Thank you.
Waiting for your reply message online!
The storage path for resource files is as follows: D: \ AI Upscaler \ upscaler main \ main
![微信图片_20240220162534](https://github.com/hollowaykeanho/Upscaler/assets/24792784/99581f6f-fb90-4a1b-88e0-4e08eb71956b)

### Current Researched Artifacts [COMPULSORY]

Hello, my friend

I encountered a problem while using Upscaler and sought help. I sent you an email but didn't see your reply! The specific issues are as follows:

I have downloaded the latest version of Upscaler 0.7 and also configured the environment variables for the OS system. I have installed the C++runtime library support and video processing plugins, but an error occurred when running start.cmd (as shown in the picture below). At the same time, I searched for the ini \ windows.ps1 file but couldn't find the problem. Please follow my path and optimize how to write the start.cmd and run.bat files.

Thank you.
Waiting for your reply message online!
The storage path for resource files is as follows: D: \ AI Upscaler \ upscaler main \ main
![微信图片_20240220162534](https://github.com/hollowaykeanho/Upscaler/assets/24792784/99581f6f-fb90-4a1b-88e0-4e08eb71956b)

**Comment by mflyskym1** [comment]
Hello teacher:I downloaded the latest version of upscaler models v0.7.0 according to your user manual and installation instructions. I also set the system environment variable and configured the path to start.cmd, but upscaler still did not run successfully.Please follow my path and optimize how to write the start.cmd and run.bat files.
Thank you very much!
My personal PC machine is an old machine from 5 years ago, with the following configuration:
Operating system OS Windows Version 10,
CPU Intel (R) Core (TM) i7-9700 CPU @ 3.00GHz,
RAM 16 GB
Graphics card: NVIDIA GeForce GTX 1660

Resource file storage path：D:\AI Upscaler\Upscaler-main\start.cmd

**Comment by Joly0** [comment]
Hey, thats probably an issue with this line of code https://github.com/hollowaykeanho/Upscaler/blob/9ba0c87bc79ab4598366ee3fd12b07cedda86cda/init/windows.ps1#L331

Could you please adjust it to this:
Powershell.exe -NoProfile -Command "Get-Help `"$PSScriptRoot\windows.ps1`""

Otherwise running start.cmd without any parameters just shows the normal help instructions.

**Comment by mflyskym1** [comment]
Thank you for your reply. Please follow the path in my previous post to modify the init/windows.ps1 file or provide a start.cmd file. Thank you very much!

**Comment by mflyskym1** [comment]
> 嘿，这可能是这行代码的问题
> 
> https://github.com/hollowaykeanho/Upscaler/blob/9ba0c87bc79ab4598366ee3fd12b07cedda86cda/init/windows.ps1#L331
> 
> 您能否将其调整为： Powershell.exe -NoProfile -Command "Get-Help `"$PSScriptRoot\windows.ps1`""
> 
> 否则，运行不带任何参数的start.cmd仅显示正常的帮助说明。

------------------------
According to your prompt, I have modified the \ windows.ps1 file and it still shows an error! Please help!
![11](https://github.com/hollowaykeanho/Upscaler/assets/24792784/00b5a67d-5df4-40fb-9a5e-b080cc548adf)
![12](https://github.com/hollowaykeanho/Upscaler/assets/24792784/31f3f953-f8e6-4f06-9d9f-3f8bedda2a4f)

**Comment by Joly0** [comment]
My bad, github made some characters disappear. You have to enter this code:
```
Powershell.exe -NoProfile -Command "Get-Help `"$PSScriptRoot\windows.ps1`""
```

**Comment by mflyskym1** [comment]
> 嘿，这可能是这行代码的问题
> 
> https://github.com/hollowaykeanho/Upscaler/blob/9ba0c87bc79ab4598366ee3fd12b07cedda86cda/init/windows.ps1#L331
> 
> 您能否将其调整为： Powershell.exe -NoProfile -Command "Get-Help `"$PSScriptRoot\windows.ps1`""
> 
> 否则，运行不带任何参数的start.cmd仅显示正常的帮助说明。

-----------------------------------
Please modify the start.cmd and run.bat files according to my storage path (D: \ AI Upscaler \ upscaler main \ main \ start. cmd). Thank you very much!

**Comment by Joly0** [comment]
I got it working. Change that line to:
```
Powershell.exe -NoProfile -Command "Get-Help '$PSScriptRoot\windows.ps1'"
```

and change this line
https://github.com/hollowaykeanho/Upscaler/blob/9ba0c87bc79ab4598366ee3fd12b07cedda86cda/init/windows.ps1#L337
to
```
Powershell.exe -NoProfile -Command "Get-Help '$PSScriptRoot\windows.ps1' -full"
```

**Comment by hollowaykeanho** [comment]
确定一下： 当您打开包装时，有移动那`start.cmd`吗？ 开头的地址是有 **main** (`D: \ AI Upscaler \ upscaler main \ main`) 而现在是没有的 (`D: \ AI Upscaler \ upscaler main`)。文件地址是不能移动的。

如果需要操控，您必须要在`start.cmd`文件夹里 （如图）：

![2024-02-20_17-23](https://github.com/hollowaykeanho/Upscaler/assets/7259572/eb910197-9813-44e8-8a36-143ff6d5eae7)

----

Translate to English

To clarify one thing: upon upacking, is there any movement to `start.cmd` file? The ticket starts with a **main** (`D: \ AI Upscaler \ upscaler main \ main`) in the path but later's troubleshooting effort shows none (`D: \ AI Upscaler \ upscaler main`). Files are not movable though.

If you wish to operate, you have to be located inside the `start.cmd` directory (as shown in screenshot).


----

site-note:

@Joly0 , could you replicate the `v0.7.0` download and run the `start.cmd` on your side with screenshot please? It will be easier to communicate.

This problem is interim as I'm re-coding the scripts to a newer version (tracking different issue - see `init/start.sh.ps1`).

Thanks in adv!

**Comment by Joly0** [comment]
Hey @hollowaykeanho i pulled fresh from main branch and was able to replicate the issue, when running start.cmd without parameters and if the path to the .cmd or the .ps1 script has whitespaces in it. With the updated commands from my last message,  it works no issue

**Comment by hollowaykeanho** [comment]
@Joly0. No problem. Thanks ya. =) Please help guide this user while I attempt to complete the new scripts with the parallel execution and batch processing.

**Comment by mflyskym1** [comment]
> 确定一下：当你打开包装时，有移动那吗`start.cmd`？ 开头的地址是有**main** ( `D: \ AI Upscaler \ upscaler main \ main`) 而现在是没有的( `D: \ AI Upscaler \ upscaler main`)。文件地址是不能移动的。
> 
> 如果需要控制器，您必须在`start.cmd`文件夹里（如图）：
> 
> ![2024-02-20_17-23](https://private-user-images.githubusercontent.com/7259572/306206006-eb910197-9813-44e8-8a36-143ff6d5eae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0Nzg2MjIsIm5iZiI6MTcwODQ3ODMyMiwicGF0aCI6Ii83MjU5NTcyLzMwNjIwNjAwNi1lYjkxMDE5Ny05ODEzLTQ0ZTgtOGEzNi0xNDNmZjZkNWVhZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMDExODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWUwZDM2MTQ4ODFmYTdjM2FlYjkwM2EwODkwMTk5NWRiN2RlY2ZjMjg4N2U4MGY1NDk0MDRhNzVkOWU5ZGM5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7k6-MuA0xMDLfzT96s6gJbUPByAs64SqFzwbu2-nuy0)
> 
> 翻译成英文
> 
> 澄清一件事：打包后，是否有任何需要`start.cmd`归档的动作？该票证以路径中的**main** ( )开头，但后来的故障排除工作显示没有 ( )。但文件不可移动。`D: \ AI Upscaler \ upscaler main \ main``D: \ AI Upscaler \ upscaler main`
> 
> 如果您想进行操作，您必须位于该`start.cmd`目录内（如截图所示）。
> 
> 站点注释：
> 
> @Joly0，您可以复制下载并在您这边`v0.7.0`运行并附上屏幕截图吗？`start.cmd`沟通会更容易。
> 
> 这个问题是临时的，因为我正在将脚本重新编码为较新的版本（跟踪不同的问题 - 请参阅`init/start.sh.ps1`）。
> 
> 感谢广告！

是的老师，按照您第一个回复的内容，我从新下载了0.7的新版本，调整了存储路径为，D:\AI Upscaler\Upscaler-main，按照@Joly0老师的指导，现在运行start.cmd已经不报错了，您看现在的运行界面是否正确（如截图），按照操作手册，我执行图像放大操作也，，，不成功！怎么办

> 确定一下： 当您打开包装时，有移动那`start.cmd`吗？ 开头的地址是有 **main** (`D: \ AI Upscaler \ upscaler main \ main`) 而现在是没有的 (`D: \ AI Upscaler \ upscaler main`)。文件地址是不能移动的。
> 
> 如果需要操控，您必须要在`start.cmd`文件夹里 （如图）：
> 
> ![2024-02-20_17-23](https://private-user-images.githubusercontent.com/7259572/306206006-eb910197-9813-44e8-8a36-143ff6d5eae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NzkyNTgsIm5iZiI6MTcwODQ3ODk1OCwicGF0aCI6Ii83MjU5NTcyLzMwNjIwNjAwNi1lYjkxMDE5Ny05ODEzLTQ0ZTgtOGEzNi0xNDNmZjZkNWVhZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMDEyOTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTNiZDIzMjI0N2RmZWFkZjAxZTc3MTM1ZjQ1ZjI0Mjc5ZjYxNWUzZjI5N2NmOGIyN2UzOWRmNWI0N2Y1Y2MzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.i4PKOhu0Y9B_3ppIXvPTv2TqqUlg261QCH9Nhk5N600)
> 
> Translate to English
> 
> To clarify one thing: upon upacking, is there any movement to `start.cmd` file? The ticket starts with a **main** (`D: \ AI Upscaler \ upscaler main \ main`) in the path but later's troubleshooting effort shows none (`D: \ AI Upscaler \ upscaler main`). Files are not movable though.
> 
> If you wish to operate, you have to be located inside the `start.cmd` directory (as shown in screenshot).
> 
> site-note:
> 
> @Joly0 , could you replicate the `v0.7.0` download and run the `start.cmd` on your side with screenshot please? It will be easier to communicate.
> 
> This problem is interim as I'm re-coding the scripts to a newer version (tracking different issue - see `init/start.sh.ps1`).
> 
> Thanks in adv!

您好老师，
按照您上一个提示，我下载了最新0.7版本的存储包，并调整了存储路径为D:\AI Upscaler\Upscaler-main，但是start.cmd和ini文件在同一个目录层级，如图1、图2.
我参照@Joly0老师的方法后，运行start.cmd时已经不报错了，如下图3，但运行图片放大处理时，还是不成功，是不是操作不正确啊，请指导！
![18](https://github.com/hollowaykeanho/Upscaler/assets/24792784/daf95fb7-16a9-4803-8b7e-937744075ded)

![15](https://github.com/hollowaykeanho/Upscaler/assets/24792784/82d4ab14-f431-4d72-b3e6-bce5f28301b2)

![16](https://github.com/hollowaykeanho/Upscaler/assets/24792784/2aef4fb2-4b1b-4e45-ab7d-e006cab32ea3)

**Comment by mflyskym1** [comment]
> 我成功了。将该行更改为：
> 
> ```
> Powershell.exe -NoProfile -Command "Get-Help '$PSScriptRoot\windows.ps1'"
> ```
> 
> 并改变这一行
> 
> https://github.com/hollowaykeanho/Upscaler/blob/9ba0c87bc79ab4598366ee3fd12b07cedda86cda/init/windows.ps1#L337
> 
> 
> 到
> ```
> Powershell.exe -NoProfile -Command "Get-Help '$PSScriptRoot\windows.ps1' -full"
> ```

Thank you very much for your guidance. My friend, there is no error when running start.cmd. Next, how to enlarge the picture or video? Please guide me!
![Uploading 15.png…]()

**Comment by hollowaykeanho** [comment]
> 如下图3，但运行图片放大处理时，还是不成功，是不是操作不正确啊，请指导！
>
> Translate to English
>
> As shown in 3rd screenshot, to upscale an image, I'm still not able to operate. Please guide.

`0.0.7` 需要更多的指令。简单的方式是：

```
$ ./start.cmd --model ultrasharp --scale 4 --format webp --input 图片.jpg
```

`--model` 是您要的AI模式。
`--scale` 是您想放大的倍数 (2 = 2x; 3 = 3x; 4 = 4x)。
`--format` 是您想要的输出图片模式。
`--input` 是您的输入图片地址。

请试试看。

----

Translate to english:

`0.0.7` requires additional arguments. The simplest form is:

```
$ ./start.cmd --model ultrasharp --scale 4 --format webp --input 图片.jpg
```

`--model` is your required AI model.
`--scale` is your upscale ratio (2 = 2x; 3 = 3x; 4 = 4x).
`--format` is your output format.
`--input` is your input filepath.

Please try.

**Comment by mflyskym1** [comment]
> > 如下图3，但运行图片处理时，还是不成功放大，是不是操作不正确啊，请指导！
> > 翻译成英文
> > 如第三张截图所示，要放大图像，我仍然无法操作。请指导。
> 
> `0.0.7`需要更多的指令。简单的方式是：
> 
> ```
> $ ./start.cmd --model ultrasharp --scale 4 --format webp --input 图片.jpg
> ```
> 
> `--model`是您想要的AI模式。 `--scale`是您想要放大的倍数（2 = 2x; 3 = 3x; 4 = 4x）。 `--format`是您想要的输出图片模式。 `--input`是您的输入图片地址。
> 
> 请尝试看看。
> 
> 翻译成英文：
> 
> `0.0.7`需要额外的参数。最简单的形式是：
> 
> ```
> $ ./start.cmd --model ultrasharp --scale 4 --format webp --input 图片.jpg
> ```
> 
> `--model`是你需要的AI模型。 `--scale`是您的高档比率（2 = 2x；3 = 3x；4 = 4x）。 `--format`是你的输出格式。 `--input`是您的输入文件路径。
> 
> 请尝试。

好的，感谢指导，我尝试一下

**Comment by hollowaykeanho** [comment]
closing this question. Anything please raise a new ticket.

关了这份询问文稿。若有进展，请开新的一份文稿吧。
