### ISSUE TITLE
Supply a Zip Package for End User to Unpack

### ISSUE THREAD

**Issue by corygalyna** [hollowaykeanho/Upscaler#9]
# Description
```
Please provide a short description of what feature you're looking forward to
add into the existing repository below. Please include the story behind your
idea as well to give a better visualization of your idea.
```
The repo is too fat due to the git history of binary blobs. You need a zip packaging CI to do the job.

# Expected Behavior
```
Please specify the expected behavior of your requested feature. Some great and
helpful pointers are your expected interface (e.g. command patterns, simple
sketches of the user interface, etc).
```
User just have to download the zip package and operate as usual. Basically, the `.git` directory is removed. Moreover, you can gpg-sign the package for integrity checking.

# Current Absent Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
User is forced to download the entire git repository making it entirely difficult to use.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
Implemented already. Standing by for tonight's benchmark and release. Hopefully on Windows side everything goes smoothly. Closing this ticket.
